### ISSUE TITLE
Some examples refer to non existent files

### ISSUE THREAD

**Issue by jluzny** [kestra-io/examples#2]
Some examples (like Snowflake final.yaml) refer to a content that is not in the examples repository anymore (moved to datasets rep?).

e.g. 
invalid uri: https://raw.githubusercontent.com/kestra-io/examples/main/datasets/employees00.csv
valid uri: https://raw.githubusercontent.com/kestra-io/datasets/main/employees/employees00.csv

**Comment by anna-geller** [comment]
you're totally right! are you willing to opening a PR?

**Comment by anna-geller** [comment]
fixed this one, if you see other issue, feel free to contribute a PR or reopen this issue and point to the broken one https://github.com/kestra-io/examples/commit/881565a0ebed4cc73eda519f1b9bf29e09fb04c1
